/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: (typeof import('vue'))['computed'];
  const computedAsync: (typeof import('@vueuse/core'))['computedAsync'];
  const computedInject: (typeof import('@vueuse/core'))['computedInject'];
  const computedWithControl: (typeof import('@vueuse/core'))['computedWithControl'];
  const customRef: (typeof import('vue'))['customRef'];
  const defineComponent: (typeof import('vue'))['defineComponent'];
  const effectScope: (typeof import('vue'))['effectScope'];
  const extendRef: (typeof import('@vueuse/core'))['extendRef'];
  const getActivePinia: (typeof import('pinia'))['getActivePinia'];
  const h: (typeof import('vue'))['h'];
  const hasInjectionContext: (typeof import('vue'))['hasInjectionContext'];
  const inject: (typeof import('vue'))['inject'];
  const isNullish: (typeof import('@tb-dev/utils'))['isNullish'];
  const isRef: (typeof import('vue'))['isRef'];
  const markRaw: (typeof import('vue'))['markRaw'];
  const nextTick: (typeof import('vue'))['nextTick'];
  const onActivated: (typeof import('vue'))['onActivated'];
  const onBeforeMount: (typeof import('vue'))['onBeforeMount'];
  const onBeforeUnmount: (typeof import('vue'))['onBeforeUnmount'];
  const onBeforeUpdate: (typeof import('vue'))['onBeforeUpdate'];
  const onClickOutside: (typeof import('@vueuse/core'))['onClickOutside'];
  const onDeactivated: (typeof import('vue'))['onDeactivated'];
  const onKeyStroke: (typeof import('@vueuse/core'))['onKeyStroke'];
  const onMounted: (typeof import('vue'))['onMounted'];
  const onScopeDispose: (typeof import('vue'))['onScopeDispose'];
  const onUnmounted: (typeof import('vue'))['onUnmounted'];
  const provide: (typeof import('vue'))['provide'];
  const reactive: (typeof import('vue'))['reactive'];
  const readonly: (typeof import('vue'))['readonly'];
  const ref: (typeof import('vue'))['ref'];
  const shallowReactive: (typeof import('vue'))['shallowReactive'];
  const shallowRef: (typeof import('vue'))['shallowRef'];
  const storeToRefs: (typeof import('pinia'))['storeToRefs'];
  const toRaw: (typeof import('vue'))['toRaw'];
  const toRef: (typeof import('vue'))['toRef'];
  const toValue: (typeof import('vue'))['toValue'];
  const triggerRef: (typeof import('vue'))['triggerRef'];
  const tryOnBeforeMount: (typeof import('@vueuse/core'))['tryOnBeforeMount'];
  const tryOnBeforeUnmount: (typeof import('@vueuse/core'))['tryOnBeforeUnmount'];
  const tryOnMounted: (typeof import('@vueuse/core'))['tryOnMounted'];
  const tryOnScopeDispose: (typeof import('@vueuse/core'))['tryOnScopeDispose'];
  const tryOnUnmounted: (typeof import('@vueuse/core'))['tryOnUnmounted'];
  const unref: (typeof import('vue'))['unref'];
  const until: (typeof import('@vueuse/core'))['until'];
  const useActiveElement: (typeof import('@vueuse/core'))['useActiveElement'];
  const useArrayDifference: (typeof import('@vueuse/core'))['useArrayDifference'];
  const useArrayEvery: (typeof import('@vueuse/core'))['useArrayEvery'];
  const useArrayFilter: (typeof import('@vueuse/core'))['useArrayFilter'];
  const useArrayFind: (typeof import('@vueuse/core'))['useArrayFind'];
  const useArrayFindIndex: (typeof import('@vueuse/core'))['useArrayFindIndex'];
  const useArrayFindLast: (typeof import('@vueuse/core'))['useArrayFindLast'];
  const useArrayIncludes: (typeof import('@vueuse/core'))['useArrayIncludes'];
  const useArrayJoin: (typeof import('@vueuse/core'))['useArrayJoin'];
  const useArrayMap: (typeof import('@vueuse/core'))['useArrayMap'];
  const useArrayReduce: (typeof import('@vueuse/core'))['useArrayReduce'];
  const useArraySome: (typeof import('@vueuse/core'))['useArraySome'];
  const useArrayUnique: (typeof import('@vueuse/core'))['useArrayUnique'];
  const useAsyncState: (typeof import('@vueuse/core'))['useAsyncState'];
  const useCurrentElement: (typeof import('@vueuse/core'))['useCurrentElement'];
  const useDraggable: (typeof import('@vueuse/core'))['useDraggable'];
  const useElementBounding: (typeof import('@vueuse/core'))['useElementBounding'];
  const useElementHover: (typeof import('@vueuse/core'))['useElementHover'];
  const useElementSize: (typeof import('@vueuse/core'))['useElementSize'];
  const useElementVisibility: (typeof import('@vueuse/core'))['useElementVisibility'];
  const useEventListener: (typeof import('@vueuse/core'))['useEventListener'];
  const useFetch: (typeof import('@vueuse/core'))['useFetch'];
  const useFocus: (typeof import('@vueuse/core'))['useFocus'];
  const useFocusWithin: (typeof import('@vueuse/core'))['useFocusWithin'];
  const useIntersectionObserver: (typeof import('@vueuse/core'))['useIntersectionObserver'];
  const useLocalStorage: (typeof import('@vueuse/core'))['useLocalStorage'];
  const useMounted: (typeof import('@vueuse/core'))['useMounted'];
  const useMouse: (typeof import('@vueuse/core'))['useMouse'];
  const useMouseInElement: (typeof import('@vueuse/core'))['useMouseInElement'];
  const useMutationObserver: (typeof import('@vueuse/core'))['useMutationObserver'];
  const useObjectUrl: (typeof import('@vueuse/core'))['useObjectUrl'];
  const useOnline: (typeof import('@vueuse/core'))['useOnline'];
  const usePageLeave: (typeof import('@vueuse/core'))['usePageLeave'];
  const useParentElement: (typeof import('@vueuse/core'))['useParentElement'];
  const useResizeObserver: (typeof import('@vueuse/core'))['useResizeObserver'];
  const useRoute: (typeof import('vue-router'))['useRoute'];
  const useRouter: (typeof import('vue-router'))['useRouter'];
  const useSessionStorage: (typeof import('@vueuse/core'))['useSessionStorage'];
  const useStorage: (typeof import('@vueuse/core'))['useStorage'];
  const useWindowScroll: (typeof import('@vueuse/core'))['useWindowScroll'];
  const useWindowSize: (typeof import('@vueuse/core'))['useWindowSize'];
  const watch: (typeof import('vue'))['watch'];
  const watchAtMost: (typeof import('@vueuse/core'))['watchAtMost'];
  const watchDebounced: (typeof import('@vueuse/core'))['watchDebounced'];
  const watchDeep: (typeof import('@vueuse/core'))['watchDeep'];
  const watchEffect: (typeof import('vue'))['watchEffect'];
  const watchIgnorable: (typeof import('@vueuse/core'))['watchIgnorable'];
  const watchImmediate: (typeof import('@vueuse/core'))['watchImmediate'];
  const watchOnce: (typeof import('@vueuse/core'))['watchOnce'];
  const watchPausable: (typeof import('@vueuse/core'))['watchPausable'];
  const watchPostEffect: (typeof import('vue'))['watchPostEffect'];
  const watchSyncEffect: (typeof import('vue'))['watchSyncEffect'];
  const watchThrottled: (typeof import('@vueuse/core'))['watchThrottled'];
  const watchTriggerable: (typeof import('@vueuse/core'))['watchTriggerable'];
  const watchWithFilter: (typeof import('@vueuse/core'))['watchWithFilter'];
  const whenever: (typeof import('@vueuse/core'))['whenever'];
}
// for type re-export
declare global {
  // @ts-ignore
  export type { MaybeArray, MaybePromise, Nullish, PartialNullish } from '@tb-dev/utility-types';
  import('@tb-dev/utility-types');
  // @ts-ignore
  export type {
    CSSProperties,
    Component,
    ComponentInstance,
    MaybeRefOrGetter,
    Ref,
    ShallowRef,
    VNode
  } from 'vue';
  import('vue');
}
